### ISSUE TITLE
SSLError: [Errno 2] No such file or directory 

### ISSUE THREAD

**Issue by speedplane** [xsleonard/pystmark#14]
I've started getting the following Traceback when sending to Postmark:

```
Traceback (most recent call last):
  File "../updater\CrossPlatform.py", line 1494, in _send_email_postmark
    resp = pystmark.send(message, api_key = passwords.postmark_apikey)
  File "..\libs\pystmark.py", line 96, in send
    secure=secure, test=test, **request_args)
  File "..\libs\pystmark.py", line 1007, in send
    return self._request(url, data=data, headers=headers, **request_args)
  File "..\libs\pystmark.py", line 891, in _request
    response = requests.request(self.method, url, **kwargs)
  File "..\libs\requests\api.py", line 44, in request
    return session.request(method=method, url=url, **kwargs)
  File "..\libs\requests\sessions.py", line 456, in request
    resp = self.send(prep, **send_kwargs)
  File "..\libs\requests\sessions.py", line 559, in send
    r = adapter.send(request, **kwargs)
  File "..\libs\requests\adapters.py", line 382, in send
    raise SSLError(e, request=request)
SSLError: [Errno 2] No such file or directory
```

The URL this call is sending to is: `https://api.postmarkapp.com/email`

The keyword arguments are:

```
{'data': '{"From": "admin@docketalarm.com", 
           "To": "mes65@<REDACTED>", 
           "Cc": "michael.sander@<REDACTED>", 
           "HtmlBody": "<p>html_content: test email: function _send_email_postmark at 0x0000000005E8F438.</p>", 
           "Headers": [{"Name": "X-Docket-Alarm", "Value": "Test Email"}], 
           "TrackOpens": true, "Tag": "testing", 
           "TextBody": "text_content: test email: function _send_email_postmark at 0x0000000005E8F438.",
           "Subject": "DA Email Test"}',
 'headers': {'Accept': 'application/json',
             'Content-Type': 'application/json',
           'X-Postmark-Server-Token': '<REDACTED>'}}
```

I monkey-patched `pystmark.py` on line 891 adding `verify=False` to the call to the requests library. That turns off SSL authentication checking, and appears to fix the issue. But ideally, I'd like to be able to use SSL.

**Comment by webbrain-one** [comment]
Hi, I opened [PR #36](https://github.com/xsleonard/pystmark/pull/36) to address this. It fixes the SSL verification handling so the request uses the proper CA certificate bundle, resolving the `SSLError: [Errno 2]` while keeping SSL enabled.
